### PR TITLE
Robbing Fix, Missing End Func

### PR DESCRIPTION
**Pull request by EchoStudioss**
hardcoded the lang as this was a personal server file i used to use, however everything else is what worked to fix my robbing not working. 

Credits @Sharkiiie

### CODE REVIEW

**Comment by jessplaysit** [comment]
this is still not working for me, I can rob players inventory but once the player gets robbed they cant access inventory after unless you check them into the hospital

**Comment by Sharkiiie** [comment]
The patch for robbing was really just a hotfix.
This pr has a lot of linting, lang changes, etc. that aren't needed just to get the robbing working.

Just pull out the NUI callback, the client event, the modified `OpenInventoryById` func and server event for it.
I haven't taken a look at the rest of the pr, but it may have some changes specific to his server, and iirc this was already a modified version of ps-inv, so the rest of the pr might be invalid anyway.

**Comment by jessplaysit** [comment]
> The patch for robbing was really just a hotfix. This pr has a lot of linting, lang changes, etc. that aren't needed just to get the robbing working.
> 
> Just pull out the NUI callback, the client event, the modified `OpenInventoryById` func and server event for it. I haven't taken a look at the rest of the pr, but it may have some changes specific to his server, and iirc this was already a modified version of ps-inv, so the rest of the pr might be invalid anyway.

ty i will have to get help on that i am not a coder by any means but i appreciate the help

**Comment by MonkeyWhisper** [comment]
> hardcoded the lang as this was a personal server file i used to use, however everything else is what worked to fix my robbing not working.
> 
> Credits @Sharkiiie

Reopen PR with proper lang files and there are too many things here that aren't needed and has been changed for no real reason

**Pull request closed without merging**
